#config.py
config_dict = {'file_parameters': dict(file_location = 'MeasurementProtocolTestFile.csv',
                                       file_delimiter = ',',
                                       file_headers = ['Timestamp', 'TealiumID', 'Call', 'Set', 'Held'],
                                       time_format = '%m/%d/%Y %I:%M',
                                       event_flag = '1'),
              'measurement_protocol': dict(properties = ['UA-114693333-1', 'UA-115180719-1'],
                                           protocol_version = '1',
                                           event_param = 'ea',
                                           environments = dict(prod_domain = 'https://ssl.google-analytics.com/collect',
                                                              debug_domain = 'https://ssl.google-analytics.com/debug/collect')),
              'dimension_settings': dict(flag_dimension = 'cd1',
                                         flag_value = 'Offline Process',
                                         event_category = 'Conversion',
                                         hit_type = 'event',
                                         data_source = 'CRM',
                                         events = list([dict(header = 'Call',
                                                             dimension_index = 'cd2',
                                                             event_action = 'Phone Call',
                                                             event_value = '1'),
                                                        dict(header = 'Set',
                                                             dimension_index = 'cd3',
                                                             event_action = 'Set Appointment',
                                                             event_value = '1'),
                                                        dict(header = 'Held',
                                                             dimension_index = 'cd4',
                                                             event_action = 'Held Appointment',
                                                             event_value = '1')]))}